language: node_js
node_js:
 - "4.2.0"
env:
  - NODE_VERSION=4.2.0 CC=clang CXX=clang++
before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
 - nvm install v4.2.0
 - nvm use v4.2.0
before_script:
 - npm install -g bower
 - npm install -g karma --save-dev
 - npm install -g gulp
 - npm install -g karma-cli
 - bower install
script:
 - gulp ci-build
