language: node_js
node_js:
 - "4.2.0"
before_script:
 - npm install -g bower
 - npm install -g karma --save-dev
 - npm install -g gulp
 - npm install -g karma-cli
 - bower install
script:
 - gulp ci-validate
